#!/usr/bin/env bash
#
# Hermes integration installer for the Commerce Control Plane.
#
# The Node package owns the Mode-A security boundary. This script is deliberately
# thin integration glue: install locked dependencies, build, create stable local
# entrypoint wrappers, validate the package, and optionally register the MCP
# launcher with Hermes.
#
# It does NOT duplicate wallet-secret scrubbing. Both generated wrappers execute
# the hardened Node launchers under dist/launch/, which scrub wallet/signing
# authority and force the Mode-A gates before importing application code.
#
# It also does NOT infer a repository/workspace from this package's monorepo
# location. By default COMMERCE_REPO_ROOT remains unset, so the package uses the
# process working directory. Use --workspace PATH only when a stable explicit
# workspace is desired for product inspection/evidence export.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

HERMES_HOME="${HERMES_HOME:-${HOME}/.hermes}"
INSTALL_DIR="${HERMES_HOME}/commerce-control"
STATE_ROOT="${INSTALL_DIR}/state"
LOG_FILE="${INSTALL_DIR}/install.log"
MCP_NAME="commerce-control"
MCP_WRAPPER="${INSTALL_DIR}/commerce-control-mcp.sh"
CLI_WRAPPER="${INSTALL_DIR}/commerce-control-cli.sh"

SKIP_DEPS=0
SKIP_REGISTER=0
FORCE_REREGISTER=0
WORKSPACE_ROOT=""

log() { printf '[install] %s\n' "$*"; }
fail() { printf '[install] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'USAGE'
Usage: install-hermes-commerce-control.sh [options]

  --skip-deps          do not run "npm ci" (use the tree already installed)
  --skip-register      install and verify locally, but do not touch Hermes
  --force              remove and re-add an existing commerce-control MCP entry
  --workspace PATH     pin COMMERCE_REPO_ROOT to an explicit existing workspace
                       in the generated wrappers; default is no override
  -h, --help           show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-deps)
      SKIP_DEPS=1
      shift
      ;;
    --skip-register)
      SKIP_REGISTER=1
      shift
      ;;
    --force)
      FORCE_REREGISTER=1
      shift
      ;;
    --workspace)
      [[ $# -ge 2 ]] || fail "--workspace requires a path"
      [[ -d "$2" ]] || fail "workspace does not exist or is not a directory: $2"
      WORKSPACE_ROOT="$(cd "$2" && pwd)"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# ---------------------------------------------------------------- preflight

log "package root: ${PACKAGE_ROOT}"
if [[ -n "${WORKSPACE_ROOT}" ]]; then
  log "explicit workspace root: ${WORKSPACE_ROOT}"
else
  log "workspace root: not pinned (runtime current working directory)"
fi

command -v node >/dev/null 2>&1 || fail "node is not on PATH"
command -v npm >/dev/null 2>&1 || fail "npm is not on PATH"

NODE_VERSION="$(node -p 'process.versions.node')"
node -e '
  const [major, minor] = process.versions.node.split(".").map(Number);
  if (major !== 24 || minor < 15) process.exit(1);
' || fail "Node >=24.15.0 <25 is required for this package; found ${NODE_VERSION}"
log "node ${NODE_VERSION}"

node -e 'import("node:sqlite").then(m=>{if(typeof m.DatabaseSync!=="function")process.exit(1)}).catch(()=>process.exit(1))' \
  || fail "built-in node:sqlite DatabaseSync is unavailable on this runtime"
log "built-in node:sqlite available"

# ------------------------------------------------------- dependencies + build

cd "${PACKAGE_ROOT}"

if [[ "${SKIP_DEPS}" -eq 0 ]]; then
  [[ -f package-lock.json ]] || fail "package-lock.json is missing; refusing to install unlocked dependencies"
  log "installing exact locked dependencies (npm ci)"
  npm ci
else
  log "skipping npm ci by request"
fi

log "compiling TypeScript"
npm run build

DIRECT_CLI_ENTRY="${PACKAGE_ROOT}/dist/cli.js"
CLI_ENTRY="${PACKAGE_ROOT}/dist/launch/cli.js"
MCP_ENTRY="${PACKAGE_ROOT}/dist/launch/mcp.js"
[[ -f "${DIRECT_CLI_ENTRY}" ]] || fail "build did not produce ${DIRECT_CLI_ENTRY}"
[[ -f "${CLI_ENTRY}" ]] || fail "build did not produce ${CLI_ENTRY}"
[[ -f "${MCP_ENTRY}" ]] || fail "build did not produce ${MCP_ENTRY}"
log "compiled direct + hardened entrypoints present"

# ------------------------------------------------------------- install layout

mkdir -p "${INSTALL_DIR}" "${STATE_ROOT}"
log "install directory: ${INSTALL_DIR}"

write_wrapper() {
  local target_path="$1" entry="$2" title="$3"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# %s\n' "${title}"
    printf '# Generated by install-hermes-commerce-control.sh — regenerate rather than edit.\n'
    printf 'set -euo pipefail\n'
    printf 'export COMMERCE_STATE_ROOT=%q\n' "${STATE_ROOT}"
    if [[ -n "${WORKSPACE_ROOT}" ]]; then
      printf 'export COMMERCE_REPO_ROOT=%q\n' "${WORKSPACE_ROOT}"
    fi
    printf 'exec node %q "$@"\n' "${entry}"
  } > "${target_path}"
  chmod 0755 "${target_path}"
}

write_wrapper "${MCP_WRAPPER}" "${MCP_ENTRY}" "Stable Hermes MCP entrypoint for the Commerce Control Plane."
write_wrapper "${CLI_WRAPPER}" "${CLI_ENTRY}" "Stable CLI entrypoint for the Commerce Control Plane."
log "wrote MCP wrapper: ${MCP_WRAPPER}"
log "wrote CLI wrapper: ${CLI_WRAPPER}"

# ------------------------------------------------- wallet-secret scrub proof

# The direct implementation is the control: it should see the fake canary and
# report an unhealthy doctor. The hardened launcher should remove it before the
# application is imported. Never print the canary value.
read_wallet_flag() {
  printf '%s' "$1" | node -e '
    let s = "";
    process.stdin.on("data", (d) => { s += d; }).on("end", () => {
      try {
        const doc = JSON.parse(s);
        process.stdout.write(String(doc.data.walletSecretPresent));
      } catch {
        process.stdout.write("error");
      }
    });
  '
}

UNSCRUBBED_JSON="$(
  PIPRAIL_PRIVATE_KEY=canary-not-a-real-key \
  COMMERCE_STATE_ROOT="${STATE_ROOT}" \
  node "${DIRECT_CLI_ENTRY}" doctor --json 2>/dev/null || true
)"
if [[ "$(read_wallet_flag "${UNSCRUBBED_JSON}")" != "true" ]]; then
  fail "direct doctor did not detect the wallet canary; the control check is invalid"
fi
log "confirmed: direct implementation detects a wallet-secret-shaped variable"

SCRUBBED_JSON="$(
  PIPRAIL_PRIVATE_KEY=canary-not-a-real-key \
  "${CLI_WRAPPER}" doctor --json 2>/dev/null || true
)"
if [[ "$(read_wallet_flag "${SCRUBBED_JSON}")" != "false" ]]; then
  fail "hardened CLI launcher did not remove the wallet canary"
fi
log "confirmed: hardened Node launcher removes wallet authority before application import"

# -------------------------------------------------------- hostile gate proof

MODE_A_JSON="$(
  COMMERCE_MODE=B \
  EXTERNAL_WRITES_ENABLED=true \
  LIVE_VALUE_MOVEMENT_ENABLED=true \
  "${CLI_WRAPPER}" doctor --json 2>/dev/null || true
)"

printf '%s' "${MODE_A_JSON}" | node -e '
let s = "";
process.stdin.on("data", (d) => { s += d; }).on("end", () => {
  const doc = JSON.parse(s);
  const data = doc.data ?? {};
  if (data.mode !== "A") process.exit(1);
  if (data.externalWritesEnabled !== false) process.exit(1);
  if (data.liveValueMovementEnabled !== false) process.exit(1);
});
' || fail "hardened launcher did not force the Mode-A gates"
log "confirmed: hostile inherited gate values normalize to Mode A"

# ------------------------------------------------------------------- doctor

log "running doctor through the hardened installed wrapper"
DOCTOR_JSON="$("${CLI_WRAPPER}" doctor --json 2>/dev/null || true)"

printf '%s' "${DOCTOR_JSON}" | node -e '
let s = "";
process.stdin.on("data", (d) => { s += d; }).on("end", () => {
  let doc;
  try { doc = JSON.parse(s); } catch {
    process.stderr.write("[install] ERROR: doctor produced no parseable JSON\n");
    process.exit(1);
  }
  const data = doc.data ?? {};
  for (const check of data.checks ?? []) {
    process.stderr.write(`[install]   ${check.status.toUpperCase().padEnd(4)} ${check.id}\n`);
  }
  if (data.mode !== "A") { process.stderr.write("[install] ERROR: mode is not A\n"); process.exit(1); }
  if (data.externalWritesEnabled !== false) { process.stderr.write("[install] ERROR: external writes enabled\n"); process.exit(1); }
  if (data.liveValueMovementEnabled !== false) { process.stderr.write("[install] ERROR: live value movement enabled\n"); process.exit(1); }
  if (data.walletSecretPresent !== false) { process.stderr.write("[install] ERROR: a wallet secret is present\n"); process.exit(1); }
  if (doc.ok !== true) { process.stderr.write("[install] ERROR: doctor reported an unhealthy install\n"); process.exit(1); }
});
' || fail "doctor refused this installation; not registering with Hermes"
log "doctor healthy: mode A, both gates false, no wallet secret"

# --------------------------------------------------------- local MCP handshake

log "verifying the hardened MCP entrypoint answers a stdio handshake"
HANDSHAKE_OUT="$(
  printf '%s\n%s\n%s\n' \
    '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"installer","version":"1.0.0"}}}' \
    '{"jsonrpc":"2.0","method":"notifications/initialized"}' \
    '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}' \
    | PIPRAIL_PRIVATE_KEY=canary-not-a-real-key "${MCP_WRAPPER}" 2>/dev/null
)"

printf '%s' "${HANDSHAKE_OUT}" | node -e '
const EXPECTED = [
  "commerce_discover_services","commerce_discover_work","commerce_export_evidence",
  "commerce_inspect","commerce_prepare_claim","commerce_prepare_publish",
  "commerce_prepare_purchase","commerce_probe","commerce_quote","commerce_sources",
  "commerce_status",
].sort();
const FORBIDDEN = [
  "commerce_pay","commerce_purchase","commerce_claim","commerce_submit","commerce_settle",
  "commerce_transfer","commerce_withdraw","commerce_fund","commerce_publish",
  "piprail_pay_request","pay","purchase","claim","submit","settle","transfer","withdraw","publish",
];
let s = "";
process.stdin.on("data", (d) => { s += d; }).on("end", () => {
  const lines = s.split("\n").filter((l) => l.trim() !== "");
  for (const line of lines) {
    const msg = JSON.parse(line);
    if (msg.jsonrpc !== "2.0") { process.stderr.write("[install] ERROR: non-protocol stdout\n"); process.exit(1); }
  }
  const listed = lines.map((l) => JSON.parse(l)).find((m) => m.id === 2);
  const names = (listed?.result?.tools ?? []).map((t) => t.name).sort();
  if (JSON.stringify(names) !== JSON.stringify(EXPECTED)) {
    process.stderr.write(`[install] ERROR: unexpected tool set: ${names.join(",")}\n`);
    process.exit(1);
  }
  for (const bad of FORBIDDEN) {
    if (names.includes(bad)) { process.stderr.write(`[install] ERROR: forbidden tool ${bad}\n`); process.exit(1); }
  }
  process.stderr.write(`[install]   ${names.length} tools, no live-action tool present\n`);
});
' || fail "the MCP entrypoint did not expose the expected safe tool set"
log "MCP handshake verified"

# --------------------------------------------------------- Hermes registration

if [[ "${SKIP_REGISTER}" -eq 1 ]]; then
  log "skipping Hermes registration by request"
else
  if ! command -v hermes >/dev/null 2>&1; then
    log "WARNING: hermes is not on PATH; skipping registration (degraded)"
  else
    export HERMES_NONINTERACTIVE=1
    HERMES_VERSION="$(hermes --version 2>&1 | head -1 || true)"
    log "hermes: ${HERMES_VERSION}"

    MCP_HELP="$(hermes mcp --help 2>&1 || true)"
    printf '%s' "${MCP_HELP}" | grep -q ' add ' \
      || fail "this Hermes build does not support 'hermes mcp add'"
    if printf '%s' "${MCP_HELP}" | grep -q -- '--command'; then
      :
    elif hermes mcp add --help 2>&1 | grep -q -- '--command'; then
      :
    else
      fail "this Hermes build does not support stdio MCP registration via --command"
    fi
    log "hermes mcp add --command is supported"

    EXISTING="$(hermes mcp list 2>&1 || true)"
    if printf '%s' "${EXISTING}" | grep -q "${MCP_NAME}"; then
      if [[ "${FORCE_REREGISTER}" -eq 1 ]]; then
        log "removing existing ${MCP_NAME} entry"
        hermes mcp remove "${MCP_NAME}" || log "WARNING: remove reported a problem"
      else
        log "${MCP_NAME} is already registered; pass --force to re-register"
      fi
    fi

    if ! hermes mcp list 2>&1 | grep -q "${MCP_NAME}"; then
      log "registering ${MCP_NAME} (stdio, no credentials)"
      if hermes mcp add "${MCP_NAME}" --command "${MCP_WRAPPER}" --connect-timeout 90; then
        log "registered ${MCP_NAME}"
      else
        log "WARNING: 'hermes mcp add' failed; the local install is still valid (degraded)"
      fi
    fi

    log "hermes mcp list:"
    hermes mcp list 2>&1 | sed 's/^/[install]   /' || true

    if hermes mcp list 2>&1 | grep -q "${MCP_NAME}"; then
      log "verifying the registered server responds"
      hermes mcp test "${MCP_NAME}" 2>&1 | sed 's/^/[install]   /' || log "WARNING: 'hermes mcp test' reported a problem"
    fi
  fi
fi

# ------------------------------------------------------------------- summary

{
  printf 'installed_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'package_root=%s\n' "${PACKAGE_ROOT}"
  printf 'workspace_root=%s\n' "${WORKSPACE_ROOT:-<runtime-cwd>}"
  printf 'mcp_wrapper=%s\n' "${MCP_WRAPPER}"
  printf 'cli_wrapper=%s\n' "${CLI_WRAPPER}"
  printf 'state_root=%s\n' "${STATE_ROOT}"
  printf 'node=%s\n' "${NODE_VERSION}"
  printf 'mcp_name=%s\n' "${MCP_NAME}"
  printf 'mode=A external_writes=false live_value_movement=false wallet_secret=false\n'
} >> "${LOG_FILE}"

log "done. Log: ${LOG_FILE}"
log "CLI:  ${CLI_WRAPPER} status --json"
log "MCP:  ${MCP_WRAPPER}"
